# Numpy exercises

In [2]:
import numpy as np

**1. Create a null vector of size 10**

In [9]:
a = np.zeros(10)

**2. Create a null vector of size 10 but the fifth value which is 1**

In [16]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**3.  Create a vector with values ranging from 10 to 49**

In [18]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

**4. Reverse a vector using slicing**

By adding another colon, you can specify a step. So we have [start:stop:step].

In [20]:
arr = np.arange(2,5) 
reversed_arr = arr[::-1]
print(reversed_arr)

[4 3 2]


**5. Create a 3x3 matrix with values ranging from 0 to 8**

In [24]:
h = np.random.randint(0,9,(3,3))
h

array([[4, 0, 7],
       [7, 2, 8],
       [4, 6, 3]])

**6. Create a 5x5 identity matrix**

In [29]:
import numpy as np

n=5
z = np.zeros((n, n), dtype='int')
z[n//2,:] = 1
z[:,n//2] = 1

print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


**7. Create a 5x5 array with random values and find the minimum and maximum values**

In [34]:
a = np.random.rand(5,5)
a

array([[0.41118755, 0.43018561, 0.84178864, 0.21092145, 0.71907098],
       [0.58522193, 0.23246817, 0.73253358, 0.65424122, 0.74366638],
       [0.66587033, 0.72981288, 0.24641208, 0.37549818, 0.30275237],
       [0.72626799, 0.12392055, 0.3761216 , 0.2765102 , 0.31480515],
       [0.78416797, 0.17868903, 0.43133225, 0.24750237, 0.20178718]])

In [35]:
a.max()

0.8417886358466526

In [36]:
a.min()

0.1239205459714875

**8. Create a random vector of size 10 and find the mean value**

In [55]:
x = np.random.rand(10)
x

array([0.50976624, 0.50084146, 0.00927809, 0.48115619, 0.93068659,
       0.86275455, 0.58172778, 0.29363622, 0.96154465, 0.864341  ])

In [57]:
x.mean()

0.5995732768869053

**9. Create a 2d array with 1 on the border and 0 inside**

In [100]:
rows, cols = (2, 3) #3 elements, 2 values in each element
arr = [[1] * cols for _ in range(rows)] #creates 2D array 
#[x]*cols determines the value of 'x' inside each element

arr_np = np.array(arr)  # Convert the list to a NumPy array

arr_np

arr_np[:,1] = 0 # assigns the value 0 to all elements in the second column (index 1) of arr_np
print(arr_np)

arr_np.ndim #2 dimensions

[[1 0 1]
 [1 0 1]]


2

**10. Normalize a 5x5 random matrix**

In [101]:
#Creating an array of random samples from the standard normal distribution
f = np.random.randn(5,5) #(5,5) is the shape. 
print(f)

[[ 0.31582511 -0.49566    -0.29104336 -0.00378306  1.29646633]
 [ 0.60337546  1.39583123  1.27815202  0.24569702  2.33206284]
 [ 0.13720772  1.31562835  1.34020604  0.93592525 -0.10111558]
 [ 0.66964782 -0.58880996  0.3844713   1.3535622   0.09461146]
 [-1.59491359 -0.36936404 -3.29870335  0.17777142  0.37559615]]


**11. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [118]:
a = np.random.rand(5,3)
a

array([[0.55454634, 0.97927116, 0.46604648],
       [0.89751539, 0.19529649, 0.74659495],
       [0.73034318, 0.67840929, 0.61777388],
       [0.00670344, 0.75089209, 0.3947519 ],
       [0.27209377, 0.52293812, 0.21581143]])

In [119]:
b = np.random.rand(3,2)
b

array([[0.420791  , 0.30888182],
       [0.30441375, 0.38750477],
       [0.07200171, 0.69136575]])

In [120]:

# This will return dot product
res = np.dot(a,b)
 
 
# print resulted matrix
print(res)

[[0.56500786 0.8729701 ]
 [0.49087345 0.86907468]
 [0.55831973 0.91558426]
 [0.25982544 0.56596278]
 [0.28922296 0.43589046]]


**12. Given a 1D array, negate all elements which are between 3 and 8, in place**

In [131]:
a = np.arange(20)
a



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [137]:
a[3:9] = np.multiply(a[3:9],-1)

print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


**13. How to find common values between two arrays?**

In [159]:
a = np.arange(0, 10, 3)
b = np.arange(2,5) 

print(np.intersect1d(a, b)) 
#The np.intersect1d() function efficiently identifies and extracts common elements from 1-D arrays

[3]


In [160]:
b

array([2, 3, 4])

In [162]:
a

array([0, 3, 6, 9])

**14. How to get the dates of yesterday, today and tomorrow?**

In [174]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2024-01-07')

In [172]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D') 
yesterday

numpy.datetime64('2024-01-06')

In [173]:
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D') 
tomorrow

numpy.datetime64('2024-01-08')

**15. Create a 5x5 matrix with row values ranging from 0 to 4**

In [163]:
h = np.random.randint(0,5,(5,5))
h

array([[3, 2, 3, 3, 3],
       [2, 2, 3, 3, 2],
       [0, 0, 3, 2, 1],
       [4, 0, 4, 1, 1],
       [1, 3, 1, 3, 3]])

**16. Create a random vector of size 10 and sort it**

In [190]:
g = np.random.rand(1,10)
g

array([[0.46318936, 0.75003031, 0.43986686, 0.21655341, 0.01656409,
        0.74133112, 0.48916683, 0.85011145, 0.26918013, 0.49872682]])

In [191]:
sorted_g = np.sort(g)
sorted_g

array([[0.01656409, 0.21655341, 0.26918013, 0.43986686, 0.46318936,
        0.48916683, 0.49872682, 0.74133112, 0.75003031, 0.85011145]])

**17. Consider two random array A and B, check if they are equal**

In [201]:
arr = np.random.rand(1,10)
arr2 = np.random.rand(1,10)

result = arr == arr2 #checking element-wise if they are true 
result

array([[False, False, False, False, False, False, False, False, False,
        False]])

In [256]:
a = np.arange(0, 20)
b = np.arange(0,10) 
np.array_equal(a, b) #checking if overall it's equal

False

**18. Create random vector of size 10 and replace the maximum value by 0**

In [261]:
#creating random vector of size 10
arr = np.random.rand(10)
arr

array([0.88094928, 0.75891191, 0.44818403, 0.18119197, 0.83207056,
       0.23347018, 0.60213421, 0.42480137, 0.03852521, 0.40894108])

In [262]:
#replacing max value by 0
arr[arr.argmax()] = 0
#arr.argmax() returns the index of the maximum element in the arr array, and 
#arr[arr.argmax()] accesses that element.

arr

array([0.        , 0.75891191, 0.44818403, 0.18119197, 0.83207056,
       0.23347018, 0.60213421, 0.42480137, 0.03852521, 0.40894108])

**19. How to convert a float (32 bits) array into an integer (32 bits) in place?**

In [263]:
np.zeros((3,3), dtype='float32')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [264]:
#changing the value type to integer 
np.zeros((3,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

**20. Find the nearest value from a given value in an array**

In [265]:
def find_nearest(a, a0):
    "Element in nd array `a` closest to the scalar value `a0`"
    idx = np.abs(a - a0).argmin()
    return a.flat[idx]

In [266]:
arr = np.array([1, 4, 7, 10, 12])
given_value = 6

nearest_value = find_nearest(arr, given_value)
print(nearest_value)

7


For more exercises see [100 Numpy Exercies](https://github.com/rougier/numpy-100),